language: node_js
cache:
  directories:
    - ~/.npm
    - node_modules
node_js:
  - '16'
  - '14'
install:
  - npm install -g codecov
  - npm install
script:
  - npm run lint
  - npm test
branches:
  only: 
    - main
